### ISSUE TITLE
Migrations from a blank DB fail due to leftover squashed migrations

### ISSUE THREAD

**Issue by zrisher** [OpenSourcePolicyCenter/webapp-public#211]
When running `python manage.py migrate` with a blank database, we're presented with an error:

```
CommandError: Conflicting migrations detected (0019_outputurl_exp_comp_datetime, 0093_auto_20150326_1647 in taxbrain).
To fix them run `python manage.py makemigrations --merge`
```

If we then run `python manage.py makemigrations --merge`, we're presented with another error:

```
ValueError: Could not find common ancestor of {'0093_auto_20150326_1647', '0019_outputurl_exp_comp_datetime'}
```

Looking at [a closed django ticket](https://code.djangoproject.com/ticket/25047) and the [django migration docs](https://docs.djangoproject.com/en/1.9/topics/migrations/), we see that:

> Once you’ve squashed your migration, you should then commit it alongside the migrations it replaces and distribute this change to all running instances of your application, making sure that they run migrate to store the change in their database.

> You must then transition the squashed migration to a normal migration by:

> * Deleting all the migration files it replaces.
> * Updating all migrations that depend on the deleted migrations to depend on the squashed migration instead.
> * Removing the replaces attribute in the Migration class of the squashed migration (this is how Django tells that it is a squashed migration).

It seems like when we squashed earlier migrations 1-93, we needed to actually remove the squashed files and the `replaces` attribute. I'm unsure why Django doesn't look at the replaces attribute to determine that `'0093_auto_20150326_1647'` is actually an ancestor of `'0019_outputurl_exp_comp_datetime'` and proceed from there. But removing those files and the replaces attribute does indeed fix this issue.

**Comment by talumbau** [comment]
@zrisher my local instance of the application is now unable to do a migration. I added a field to a model over in the `dynamic` app and just ran a typical `python manage.py makemigrations; python manage.py migrate`. The error is below. 

From reading the documentation you linked to in #212, it seems to me that the error is coming about due to this step: 

```
 - Updating all migrations that depend on the deleted migrations to depend on the squashed migration instead.
```

I suspect that there could be migrations in `dynamic` that depend on deleted migrations in `taxbrain`. Do you think this is the likely cause of the problem?


```
Running migrations:
  Rendering model states... DONE
  Applying taxbrain.0001_squashed_0093_auto_20150326_1647...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "taxbrain_taxsaveinputs" already exists
```

**Comment by talumbau** [comment]
Ah, I believe I have resolved it. The migration dependencies are correct, as far as I can tell. When I run `python manage.py migrate dynamic` to add my new field to the database, it turns out that there is a dependency on a `taxbrain` migration, `0015_auto_20160201_0257`, which has a dependency chain that leads back to `0001_squashed...` in `taxbrain`. It then hits this migration and attempts to actually run it because (I'm assuming) the migration has changed so it doesn't "count" anymore as being in the migration history (the change being the removal of the "replaces" attribute). So by executing:

```
python manage.py migrate dynamic --fake-initial
```

the "create model" commands in that migration are faked. It then proceeds to my new migration: 

```
(heroku_aei)0054-tjalumbaugh:webapp talumbau$ python manage.py migrate dynamic --fake-initial
Operations to perform:
  Apply all migrations: dynamic
Running migrations:
  Rendering model states... DONE
  Applying taxbrain.0001_squashed_0093_auto_20150326_1647... FAKED
  Applying dynamic.0010_ogusaworkernodescounter... OK
```

and everything is fine. Adding the note here for other users who will almost certainly hit this.

**Comment by zrisher** [comment]
@talumbau Another interesting experiment with Django migrations. : )

It makes sense to me that migrations from other apps like Dynamic can depend on migrations from taxcalc, and from the dependency lines I see everything adds up properly (like you said). After squashing the original 93 migrations, everything done since properly points back the new squashed one.

What didn't make sense is why when you run `python manage.py migrate` it thinks you haven't run  `taxbrain.0001_squashed_0093_auto_20150326_1647` already. 

Looking at the only table I could find that seems to track previously ran migrations, it seems Django stores only the id of the migration and its app:

![image](https://cloud.githubusercontent.com/assets/1958130/14271623/9c2f10d8-faaf-11e5-975a-b5704860e050.png)

This is exactly how Rails tracks previously run migrations. It also means that changing the content of a previously run migration file won't change Django's understanding of the fact that it has already been run.

HOWEVER, what if Django had never stored that particular migration in the history, because when reading through all the previously run migrations it encountered all its `replaces`? That explains the behaviour we're seeing. Perhaps that's what you were saying above but it took me a bit to make this leap.

So I guess the proper procedure for squashing migrations is actually:

1. Generate squashed migration
2. Deleting all the migration files it replaces.
3. Updating all migrations that depend on the deleted migrations to depend on the squashed migration instead.
4. Removing the replaces attribute in the Migration class of the squashed migration (this is how Django tells that it is a squashed migration). **ONLY AFTER all contributors have rebuilt their databases.**

Fortunately, if I'm right, living between step 3 and step 4 works for both people with fresh install and those with existing databases. So I submitted #218 I add the `replaces` line back. It works for me, we just need someone with an existing database who hasn't tried your solution above to confirm this works for them too.

**Comment by talumbau** [comment]
no activity for this recently. closing for now.

**Comment by zrisher** [comment]
Sounds ok to me, you may want to merge #218 later though if other users experience the issues you had.
